require("flobilosaurus.plugins-setup")
require("flobilosaurus.core.options")
require("flobilosaurus.core.keymaps")
require("flobilosaurus.core.colorscheme")
require("flobilosaurus.plugins.comment")
require("flobilosaurus.plugins.neo-tree")
require("flobilosaurus.plugins.lualine")
require("flobilosaurus.plugins.telescope")
require("flobilosaurus.plugins.which-key")
require("flobilosaurus.plugins.vim-test")
require("flobilosaurus.plugins.alpha")
require("flobilosaurus.plugins.vim-markdown")

require("flobilosaurus.plugins.lsp.mason")
require("flobilosaurus.plugins.lsp.lspsaga")
require("flobilosaurus.plugins.lsp.lspconfig")
require("flobilosaurus.plugins.lsp.null-ls")
require("flobilosaurus.plugins.lsp.lsp-signature")
require("flobilosaurus.plugins.lsp.symbols-outline")

require("flobilosaurus.plugins.nvim-cmp")
require("flobilosaurus.plugins.treesitter")
require("flobilosaurus.plugins.gitsigns")
require("flobilosaurus.plugins.autopairs")
